### ISSUE TITLE
The gerber file seems corrupted

### ISSUE THREAD

**Issue by BoykoNeov** [sonocotta/esparagus-hifi-medialink#2]
Hi,
Thanks for sharing the project. The the gerber seems corrupted - I can't open it like an archive or with any gerber viewer I tried.

**Comment by anabolyc** [comment]
Hey @BoykoNeov. It is a simple zip archive. I just tried to pull it from the github and it opens with no issues.

**Comment by BoykoNeov** [comment]
Ah yeah, I was doing it wrong - right clicking and then "save as..." - it saves a file with the right name and extension (which mislead me), but different size and obviously contents. Sorry for the false alarm.
![image](https://github.com/sonocotta/esparagus-hifi-medialink/assets/25863802/72dc0411-0258-4a14-96df-5d401fb15fde)
